// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:800892936885:web:676d7c1c4f02e5bfedd4fc',
    messagingSenderId: '800892936885',
    projectId: 'flutter-demo-sports',
    authDomain: 'flutter-demo-sports.firebaseapp.com',
    storageBucket: 'flutter-demo-sports.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:800892936885:android:aec302864ce02226edd4fc',
    messagingSenderId: '800892936885',
    projectId: 'flutter-demo-sports',
    storageBucket: 'flutter-demo-sports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:800892936885:ios:a45ea826ec59ff58edd4fc',
    messagingSenderId: '800892936885',
    projectId: 'flutter-demo-sports',
    storageBucket: 'flutter-demo-sports.firebasestorage.app',
    iosBundleId: 'com.example.sports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:800892936885:ios:a45ea826ec59ff58edd4fc',
    messagingSenderId: '800892936885',
    projectId: 'flutter-demo-sports',
    storageBucket: 'flutter-demo-sports.firebasestorage.app',
    iosBundleId: 'com.example.sports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:800892936885:web:d4e5fe19c0a2dcb5edd4fc',
    messagingSenderId: '800892936885',
    projectId: 'flutter-demo-sports',
    authDomain: 'flutter-demo-sports.firebaseapp.com',
    storageBucket: 'flutter-demo-sports.firebasestorage.app',
  );

}
